#! /bin/sh

# simple x hot key daemon
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# set the default cursor to an arrow instead of an X
xsetroot -cursor_name left_ptr &

# deskktop wallpaper manager
nitrogen --restore &

# compositing manager
compton -bcC &

# start polybar panel
$HOME/.config/polybar/launch.sh

